version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      compatible-root-updates:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /apps/aopdf
    schedule:
      interval: weekly
    groups:
      compatible-aopdf-updates:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
